// Subtitle Service: Export standard SRT and WebVTT closed captions
import { Presentation } from '../types/presentation';

interface CaptionCue {
  startMs: number;
  endMs: number;
  text: string;
}

export function generateCaptionCues(presentation: Presentation, customDurations?: number[]): CaptionCue[] {
  const cues: CaptionCue[] = [];
  let currentMs = 0;

  for (let i = 0; i < presentation.slides.length; i++) {
    const slide = presentation.slides[i];
    const script = slide.script?.trim();
    const slideDuration = customDurations?.[i] ?? Math.max(3, slide.duration || 5);
    const slideDurationMs = slideDuration * 1000;

    if (!script) {
      currentMs += slideDurationMs;
      continue;
    }

    // Split script into sentence phrases or chunks of ~7-10 words
    const sentences = script.match(/[^.!?]+[.!?]+|[^.!?]+$/g) || [script];
    const cleanSentences = sentences.map(s => s.replace(/\[[^\]]+\]/g, '').trim()).filter(Boolean);

    if (cleanSentences.length === 0) {
      currentMs += slideDurationMs;
      continue;
    }

    // Allocate time proportionally to sentence word counts
    const totalWords = cleanSentences.reduce((acc, s) => acc + s.split(/\s+/).length, 0);
    let slideOffsetMs = 0;

    cleanSentences.forEach((sentence, sIdx) => {
      const words = sentence.split(/\s+/).length;
      const portion = totalWords > 0 ? words / totalWords : 1 / cleanSentences.length;
      // Reserve 0.5s padding at the end of slide
      const sentenceDurationMs = Math.max(1200, (slideDurationMs - 500) * portion);

      const cueStart = currentMs + slideOffsetMs;
      const cueEnd = Math.min(currentMs + slideDurationMs - 100, cueStart + sentenceDurationMs);

      cues.push({
        startMs: Math.round(cueStart),
        endMs: Math.round(cueEnd),
        text: sentence,
      });

      slideOffsetMs += sentenceDurationMs;
    });

    currentMs += slideDurationMs;
  }

  return cues;
}

// Generate SubRip (.srt) format
export function generateSRT(presentation: Presentation, customDurations?: number[]): string {
  const cues = generateCaptionCues(presentation, customDurations);
  let srt = '';

  cues.forEach((cue, index) => {
    const startTime = formatSRTTime(cue.startMs);
    const endTime = formatSRTTime(cue.endMs);
    srt += `${index + 1}\n${startTime} --> ${endTime}\n${cue.text}\n\n`;
  });

  return srt;
}

// Generate WebVTT (.vtt) format
export function generateVTT(presentation: Presentation, customDurations?: number[]): string {
  const cues = generateCaptionCues(presentation, customDurations);
  let vtt = 'WEBVTT - Generated by SlideCast Pro\n\n';

  cues.forEach((cue, index) => {
    const startTime = formatVTTTime(cue.startMs);
    const endTime = formatVTTTime(cue.endMs);
    vtt += `${index + 1}\n${startTime} --> ${endTime}\n${cue.text}\n\n`;
  });

  return vtt;
}

function formatSRTTime(ms: number): string {
  const hours = Math.floor(ms / 3600000);
  const minutes = Math.floor((ms % 3600000) / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  const milliseconds = ms % 1000;

  return `${pad(hours, 2)}:${pad(minutes, 2)}:${pad(seconds, 2)},${pad(milliseconds, 3)}`;
}

function formatVTTTime(ms: number): string {
  const hours = Math.floor(ms / 3600000);
  const minutes = Math.floor((ms % 3600000) / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  const milliseconds = ms % 1000;

  return `${pad(hours, 2)}:${pad(minutes, 2)}:${pad(seconds, 2)}.${pad(milliseconds, 3)}`;
}

function pad(num: number, size: number): string {
  let s = num.toString();
  while (s.length < size) s = '0' + s;
  return s;
}

export function downloadSubtitleFile(content: string, presentationTitle: string, format: 'srt' | 'vtt'): void {
  const cleanTitle = presentationTitle.replace(/[^a-zA-Z0-9_-]/g, '_') || 'subtitles';
  const blob = new Blob([content], { type: format === 'srt' ? 'application/x-subrip' : 'text/vtt' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${cleanTitle}_captions.${format}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
