import { SlideElement } from '../types/presentation';

export interface LayoutDefinition {
  id: string;
  name: string;
  description: string;
  iconName: string;
  createElements: (themePrimary: string, themeSecondary: string, themeText: string, themeMuted: string) => SlideElement[];
}

export const SLIDE_LAYOUTS: LayoutDefinition[] = [
  {
    id: 'title-slide',
    name: 'Title Slide',
    description: 'Impactful title, subtitle and presentation author',
    iconName: 'Layout',
    createElements: (primary, secondary, text, muted) => [
      {
        id: 'el-title',
        type: 'text',
        x: 180,
        y: 340,
        width: 1560,
        height: 180,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        text: 'The Future of Modern Technology',
        fontSize: 68,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '700',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'center',
        lineHeight: 1.2,
      },
      {
        id: 'el-subtitle',
        type: 'text',
        x: 260,
        y: 540,
        width: 1400,
        height: 100,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        text: 'Transforming Intelligence, Architecture, and Human Potential',
        fontSize: 32,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: muted,
        textAlign: 'center',
        lineHeight: 1.4,
      },
      {
        id: 'el-author',
        type: 'text',
        x: 400,
        y: 680,
        width: 1120,
        height: 60,
        rotation: 0,
        opacity: 0.9,
        zIndex: 3,
        text: 'Presented by SlideCast Studio • 2026',
        fontSize: 22,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: primary,
        textAlign: 'center',
        lineHeight: 1.4,
      },
    ],
  },
  {
    id: 'title-content',
    name: 'Title + Content',
    description: 'Header with clean multi-point narrative body',
    iconName: 'AlignLeft',
    createElements: (primary, secondary, text, muted) => [
      {
        id: 'el-heading',
        type: 'text',
        x: 140,
        y: 120,
        width: 1640,
        height: 100,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        text: 'Executive Summary & Key Milestones',
        fontSize: 54,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '700',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'el-body',
        type: 'text',
        x: 140,
        y: 280,
        width: 1640,
        height: 620,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        text: '• Accelerated innovation cycle delivering 3x faster time-to-market across all product verticals.\n\n• Seamless browser-based rendering delivering 60 FPS performance without requiring local native installations.\n\n• End-to-end multimodal narration using neural AI speech with synchronized speech-to-video alignment.\n\n• Zero-dependency video compilation running directly on Web Audio and MediaRecorder standards.',
        fontSize: 28,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'left',
        lineHeight: 1.6,
        isBulletList: true,
      },
    ],
  },
  {
    id: 'two-column',
    name: 'Two-Column',
    description: 'Side-by-side comparison or dual perspectives',
    iconName: 'Columns',
    createElements: (primary, secondary, text, muted) => [
      {
        id: 'el-title',
        type: 'text',
        x: 140,
        y: 100,
        width: 1640,
        height: 90,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        text: 'Strategic Architecture Comparison',
        fontSize: 50,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '700',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'left',
        lineHeight: 1.2,
      },
      // Column 1 Card Shape
      {
        id: 'el-col1-bg',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 140,
        y: 230,
        width: 780,
        height: 720,
        rotation: 0,
        opacity: 0.2,
        zIndex: 2,
        fillColor: primary,
        borderColor: primary,
        borderWidth: 2,
        borderRadius: 16,
      },
      {
        id: 'el-col1-text',
        type: 'text',
        x: 180,
        y: 270,
        width: 700,
        height: 640,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        text: 'Phase 1: Real-time In-Browser Generation\n\n• Instant client-side state manipulation\n• 0ms server latency on canvas modifications\n• High-fidelity drag and drop mechanics\n• Full undo/redo history rollback capabilities\n• Instant WYSIWYG visual feedback',
        fontSize: 26,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'left',
        lineHeight: 1.6,
      },
      // Column 2 Card Shape
      {
        id: 'el-col2-bg',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 1000,
        y: 230,
        width: 780,
        height: 720,
        rotation: 0,
        opacity: 0.2,
        zIndex: 2,
        fillColor: secondary,
        borderColor: secondary,
        borderWidth: 2,
        borderRadius: 16,
      },
      {
        id: 'el-col2-text',
        type: 'text',
        x: 1040,
        y: 270,
        width: 700,
        height: 640,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        text: 'Phase 2: Neural Narration & Video Pipeline\n\n• High fidelity Microsoft Edge TTS voice synthesis\n• Web Audio API multi-channel mixing\n• Frame-accurate timeline synchronization\n• 1080p 60fps MediaRecorder video packaging\n• Instant one-click file download',
        fontSize: 26,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'image-caption',
    name: 'Image + Caption',
    description: 'Central hero visual framed with descriptive narrative',
    iconName: 'Image',
    createElements: (primary, secondary, text, muted) => [
      {
        id: 'el-title',
        type: 'text',
        x: 140,
        y: 80,
        width: 1640,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        text: 'Visual Prototype Demonstration',
        fontSize: 48,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '700',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'center',
        lineHeight: 1.2,
      },
      {
        id: 'el-img',
        type: 'image',
        x: 320,
        y: 190,
        width: 1280,
        height: 640,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        src: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=80',
        objectFit: 'cover',
        borderRadius: 20,
        shadowBlur: 30,
        shadowColor: 'rgba(0, 0, 0, 0.4)',
      },
      {
        id: 'el-caption',
        type: 'text',
        x: 320,
        y: 860,
        width: 1280,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        text: 'Next-generation neural computing architectures processing real-time audio-visual data streams.',
        fontSize: 22,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: muted,
        textAlign: 'center',
        lineHeight: 1.5,
      },
    ],
  },
  {
    id: 'section-header',
    name: 'Section Header',
    description: 'Breakout slide defining a major new topic',
    iconName: 'Bookmark',
    createElements: (primary, secondary, text, muted) => [
      {
        id: 'el-decor-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 140,
        y: 380,
        width: 16,
        height: 280,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        fillColor: primary,
        borderRadius: 8,
      },
      {
        id: 'el-sec-title',
        type: 'text',
        x: 200,
        y: 380,
        width: 1560,
        height: 140,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        text: 'Part II: AI Narration & Synthesis Engine',
        fontSize: 64,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '800',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'left',
        lineHeight: 1.15,
      },
      {
        id: 'el-sec-desc',
        type: 'text',
        x: 200,
        y: 540,
        width: 1400,
        height: 120,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        text: 'Exploring Edge TTS integration, SSML prosody controls, and automatic timeline duration generation.',
        fontSize: 28,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: muted,
        textAlign: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  {
    id: 'metric-stats',
    name: 'Big Metrics & Stats',
    description: 'High-impact quantitative figures and key performance indicators',
    iconName: 'BarChart3',
    createElements: (primary, secondary, text, muted) => [
      {
        id: 'el-heading',
        type: 'text',
        x: 140,
        y: 100,
        width: 1640,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        text: 'System Performance & Benchmarks',
        fontSize: 50,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '700',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'center',
        lineHeight: 1.2,
      },
      // Stat 1
      {
        id: 'el-stat1-num',
        type: 'text',
        x: 140,
        y: 320,
        width: 480,
        height: 130,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        text: '60 FPS',
        fontSize: 84,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '800',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: primary,
        textAlign: 'center',
        lineHeight: 1.1,
      },
      {
        id: 'el-stat1-lbl',
        type: 'text',
        x: 140,
        y: 470,
        width: 480,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        text: 'Smooth Canvas Rendering Pipeline',
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'center',
        lineHeight: 1.4,
      },
      // Stat 2
      {
        id: 'el-stat2-num',
        type: 'text',
        x: 720,
        y: 320,
        width: 480,
        height: 130,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        text: '50+ Voices',
        fontSize: 84,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '800',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: secondary,
        textAlign: 'center',
        lineHeight: 1.1,
      },
      {
        id: 'el-stat2-lbl',
        type: 'text',
        x: 720,
        y: 470,
        width: 480,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        text: '30+ Global Neural Edge Locales',
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'center',
        lineHeight: 1.4,
      },
      // Stat 3
      {
        id: 'el-stat3-num',
        type: 'text',
        x: 1300,
        y: 320,
        width: 480,
        height: 130,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        text: '1080p',
        fontSize: 84,
        fontFamily: 'Outfit, sans-serif',
        fontWeight: '800',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#38bdf8',
        textAlign: 'center',
        lineHeight: 1.1,
      },
      {
        id: 'el-stat3-lbl',
        type: 'text',
        x: 1300,
        y: 470,
        width: 480,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        text: 'Crystal Clear MP4/WebM Video Export',
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fontStyle: 'normal',
        textDecoration: 'none',
        color: text,
        textAlign: 'center',
        lineHeight: 1.4,
      },
    ],
  },
  {
    id: 'blank',
    name: 'Blank',
    description: 'Empty canvas ready for complete creative freedom',
    iconName: 'Square',
    createElements: () => [],
  },
];
