import { Presentation } from '../types/presentation';
import { PRESET_THEMES } from './themes';

export const SAMPLE_PRESENTATION: Presentation = {
  id: 'presentation-demo-01',
  title: 'AI in Modern Technology: The Next Frontier',
  themeId: 'modern-dark',
  canvasWidth: 1920,
  canvasHeight: 1080,
  globalVoiceSettings: {
    voice: 'en-US-GuyNeural',
    rate: 1.0,
    pitch: 0,
    volume: 100,
  },
  pronunciationDictionary: [
    { id: 'p1', word: 'TTS', replacement: 'Text to Speech' },
    { id: 'p2', word: 'AI', replacement: 'A I' },
    { id: 'p3', word: 'HTML5', replacement: 'HTML five' },
    { id: 'p4', word: 'WebM', replacement: 'Web M' },
  ],
  masterSlide: {
    showHeader: true,
    headerText: 'SlideCast Studio • Innovation Series',
    showFooter: true,
    footerText: 'Confidential & Proprietary • 2026',
    showSlideNumber: true,
    slideNumberPosition: 'bottom-right',
    brandingText: 'SlideCast',
  },
  slides: [
    // Slide 1: Title Slide
    {
      id: 'slide-1',
      title: 'Welcome & Introduction',
      layout: 'title-slide',
      background: {
        type: 'linear-gradient',
        color: '#0f172a',
        gradientStart: '#090d16',
        gradientEnd: '#1e1b4b',
        gradientAngle: 135,
      },
      transition: {
        type: 'fade',
        duration: 0.8,
        easing: 'ease-in-out',
      },
      script: 'Welcome to SlideCast Studio. Today, we present the next frontier of web-based presentation design and artificial intelligence narration. With seamless browser execution, your ideas transform directly into high-definition synchronized video.',
      duration: 7,
      paddingDuration: 1.0,
      autoAdvance: true,
      elements: [
        {
          id: 's1-tag',
          type: 'text',
          x: 710,
          y: 220,
          width: 500,
          height: 48,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          text: 'NEXT-GENERATION PRESENTATION PLATFORM',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#38bdf8',
          backgroundColor: 'rgba(56, 189, 248, 0.12)',
          textAlign: 'center',
          lineHeight: 1.6,
          borderRadius: 20,
          borderWidth: 1,
          borderColor: 'rgba(56, 189, 248, 0.3)',
          borderStyle: 'solid',
        },
        {
          id: 's1-title',
          type: 'text',
          x: 160,
          y: 310,
          width: 1600,
          height: 180,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          text: 'AI Narration & Video Export Engine',
          fontSize: 72,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'center',
          lineHeight: 1.15,
        },
        {
          id: 's1-sub',
          type: 'text',
          x: 240,
          y: 520,
          width: 1440,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: 'Synthesizing professional presentations into full 1080p video with zero native dependencies.',
          fontSize: 30,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#94a3b8',
          textAlign: 'center',
          lineHeight: 1.4,
        },
        {
          id: 's1-author',
          type: 'text',
          x: 360,
          y: 670,
          width: 1200,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          text: 'Created with SlideCast Studio • Powered by Microsoft Edge TTS',
          fontSize: 22,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '500',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#818cf8',
          textAlign: 'center',
          lineHeight: 1.4,
        },
      ],
    },

    // Slide 2: Core Capabilities
    {
      id: 'slide-2',
      title: 'Core System Capabilities',
      layout: 'title-content',
      background: {
        type: 'linear-gradient',
        color: '#0f172a',
        gradientStart: '#0b0f19',
        gradientEnd: '#1e1b4b',
        gradientAngle: 150,
      },
      transition: {
        type: 'slide-left',
        duration: 0.6,
        easing: 'ease-in-out',
      },
      script: 'Our platform delivers three foundational pillars: an intuitive drag and drop canvas, rich Edge TTS speech synthesis with over fifty neural voices, and an in-browser video renderer that outputs crisp MP4 and WebM videos.',
      duration: 8,
      paddingDuration: 1.0,
      autoAdvance: true,
      elements: [
        {
          id: 's2-title',
          type: 'text',
          x: 140,
          y: 100,
          width: 1640,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          text: 'Core Architectural Capabilities',
          fontSize: 54,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.2,
        },
        // Box 1
        {
          id: 's2-card1',
          type: 'shape',
          shapeType: 'rounded-rect',
          x: 140,
          y: 240,
          width: 500,
          height: 520,
          rotation: 0,
          opacity: 0.25,
          zIndex: 2,
          fillColor: '#6366f1',
          borderColor: '#6366f1',
          borderWidth: 2,
          borderRadius: 16,
        },
        {
          id: 's2-card1-text',
          type: 'text',
          x: 170,
          y: 280,
          width: 440,
          height: 440,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: '🎨 Drag & Drop Editor\n\n• Flexible free-form canvas\n• Smart alignment guides\n• 8-handle resizing & rotation\n• Shapes, tables, icons & rich text\n• 10+ professional themes',
          fontSize: 24,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.6,
        },
        // Box 2
        {
          id: 's2-card2',
          type: 'shape',
          shapeType: 'rounded-rect',
          x: 710,
          y: 240,
          width: 500,
          height: 520,
          rotation: 0,
          opacity: 0.25,
          zIndex: 2,
          fillColor: '#818cf8',
          borderColor: '#818cf8',
          borderWidth: 2,
          borderRadius: 16,
        },
        {
          id: 's2-card2-text',
          type: 'text',
          x: 740,
          y: 280,
          width: 440,
          height: 440,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: '🎙️ Neural Edge TTS\n\n• 50+ natural neural voices\n• 30+ international languages\n• Rate, pitch & volume controls\n• SSML pauses & emphasis\n• Audio caching & waveforms',
          fontSize: 24,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.6,
        },
        // Box 3
        {
          id: 's2-card3',
          type: 'shape',
          shapeType: 'rounded-rect',
          x: 1280,
          y: 240,
          width: 500,
          height: 520,
          rotation: 0,
          opacity: 0.25,
          zIndex: 2,
          fillColor: '#38bdf8',
          borderColor: '#38bdf8',
          borderWidth: 2,
          borderRadius: 16,
        },
        {
          id: 's2-card3-text',
          type: 'text',
          x: 1310,
          y: 280,
          width: 440,
          height: 440,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: '🎬 1080p Video Exporter\n\n• Canvas frame stream capture\n• Web Audio synchronization\n• 20+ slide transition effects\n• Bitrate up to 12 Mbps\n• Instant browser download',
          fontSize: 24,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.6,
        },
      ],
    },

    // Slide 3: Performance Metrics
    {
      id: 'slide-3',
      title: 'Performance Benchmarks',
      layout: 'metric-stats',
      background: {
        type: 'linear-gradient',
        color: '#0f172a',
        gradientStart: '#090d16',
        gradientEnd: '#1e1b4b',
        gradientAngle: 135,
      },
      transition: {
        type: 'zoom-in',
        duration: 0.7,
        easing: 'ease-in-out',
      },
      script: 'Notice the performance benchmarks: sixty frames per second canvas rendering, over fifty supported neural voices, and video compilation in under two minutes for standard presentations.',
      duration: 7,
      paddingDuration: 1.0,
      autoAdvance: true,
      elements: [
        {
          id: 's3-heading',
          type: 'text',
          x: 140,
          y: 100,
          width: 1640,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          text: 'System Performance & Real-Time Benchmarks',
          fontSize: 52,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'center',
          lineHeight: 1.2,
        },
        // Metric 1
        {
          id: 's3-m1-bg',
          type: 'shape',
          shapeType: 'rounded-rect',
          x: 140,
          y: 280,
          width: 480,
          height: 380,
          rotation: 0,
          opacity: 0.2,
          zIndex: 2,
          fillColor: '#6366f1',
          borderColor: '#6366f1',
          borderWidth: 2,
          borderRadius: 20,
        },
        {
          id: 's3-m1-num',
          type: 'text',
          x: 140,
          y: 340,
          width: 480,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: '60 FPS',
          fontSize: 78,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#818cf8',
          textAlign: 'center',
          lineHeight: 1.1,
        },
        {
          id: 's3-m1-sub',
          type: 'text',
          x: 160,
          y: 480,
          width: 440,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          text: 'Smooth browser hardware-accelerated canvas animations',
          fontSize: 22,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '500',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#cbd5e1',
          textAlign: 'center',
          lineHeight: 1.4,
        },
        // Metric 2
        {
          id: 's3-m2-bg',
          type: 'shape',
          shapeType: 'rounded-rect',
          x: 720,
          y: 280,
          width: 480,
          height: 380,
          rotation: 0,
          opacity: 0.2,
          zIndex: 2,
          fillColor: '#a855f7',
          borderColor: '#a855f7',
          borderWidth: 2,
          borderRadius: 20,
        },
        {
          id: 's3-m2-num',
          type: 'text',
          x: 720,
          y: 340,
          width: 480,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: '50+ Voices',
          fontSize: 78,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#c084fc',
          textAlign: 'center',
          lineHeight: 1.1,
        },
        {
          id: 's3-m2-sub',
          type: 'text',
          x: 740,
          y: 480,
          width: 440,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          text: 'Natural neural edge voices across 30+ spoken languages',
          fontSize: 22,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '500',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#cbd5e1',
          textAlign: 'center',
          lineHeight: 1.4,
        },
        // Metric 3
        {
          id: 's3-m3-bg',
          type: 'shape',
          shapeType: 'rounded-rect',
          x: 1300,
          y: 280,
          width: 480,
          height: 380,
          rotation: 0,
          opacity: 0.2,
          zIndex: 2,
          fillColor: '#38bdf8',
          borderColor: '#38bdf8',
          borderWidth: 2,
          borderRadius: 20,
        },
        {
          id: 's3-m3-num',
          type: 'text',
          x: 1300,
          y: 340,
          width: 480,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: '< 2 Mins',
          fontSize: 78,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#38bdf8',
          textAlign: 'center',
          lineHeight: 1.1,
        },
        {
          id: 's3-m3-sub',
          type: 'text',
          x: 1320,
          y: 480,
          width: 440,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          text: 'Rapid 1080p video generation right on a standard laptop',
          fontSize: 22,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '500',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#cbd5e1',
          textAlign: 'center',
          lineHeight: 1.4,
        },
      ],
    },

    // Slide 4: Data Matrix / Table Slide
    {
      id: 'slide-4',
      title: 'Feature Comparison Matrix',
      layout: 'title-content',
      background: {
        type: 'linear-gradient',
        color: '#0f172a',
        gradientStart: '#070b13',
        gradientEnd: '#1e1b4b',
        gradientAngle: 160,
      },
      transition: {
        type: 'cube-left',
        duration: 0.7,
        easing: 'ease-in-out',
      },
      script: 'Here is a detailed comparison illustrating our web-first approach versus legacy desktop presentation suites. We combine instant sharing with automated studio narration and one-click video synthesis.',
      duration: 8,
      paddingDuration: 1.0,
      autoAdvance: true,
      elements: [
        {
          id: 's4-heading',
          type: 'text',
          x: 140,
          y: 100,
          width: 1640,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          text: 'Competitive Architecture Comparison',
          fontSize: 50,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.2,
        },
        {
          id: 's4-table',
          type: 'table',
          x: 140,
          y: 220,
          width: 1640,
          height: 580,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          rows: 5,
          cols: 4,
          headerBgColor: '#312e81',
          headerTextColor: '#ffffff',
          cellBgColor: 'rgba(30, 41, 59, 0.7)',
          cellTextColor: '#f1f5f9',
          borderColor: '#4338ca',
          borderWidth: 2,
          fontSize: 22,
          data: [
            ['Feature Capability', 'SlideCast Studio', 'Traditional Desktop Tools', 'Standard Online Slides'],
            ['AI Speech Narration', 'Built-in Microsoft Edge Neural TTS', 'Manual voiceover recording required', 'Not supported natively'],
            ['Video Pipeline', 'Direct 1080p Canvas & Audio Stream', 'Heavy offline rendering engine', 'Export as PDF / Static images only'],
            ['Slide Transitions', '20+ GPU-accelerated transitions', 'Desktop dependent', 'Limited basic fades'],
            ['Setup & Installation', 'Zero installation (Pure Web)', 'Large 2GB+ installer', 'Requires proprietary cloud account'],
          ],
        },
      ],
    },

    // Slide 5: Visual Showcase (Image + Caption)
    {
      id: 'slide-5',
      title: 'Visual Prototype Showcase',
      layout: 'image-caption',
      background: {
        type: 'linear-gradient',
        color: '#0f172a',
        gradientStart: '#090d16',
        gradientEnd: '#1e1b4b',
        gradientAngle: 135,
      },
      transition: {
        type: 'flip-x',
        duration: 0.8,
        easing: 'ease-in-out',
      },
      script: 'High performance web graphics empower rich data visualizations and interactive presentation stages, giving teams the speed to present with absolute confidence.',
      duration: 7,
      paddingDuration: 1.0,
      autoAdvance: true,
      elements: [
        {
          id: 's5-title',
          type: 'text',
          x: 140,
          y: 70,
          width: 1640,
          height: 70,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          text: 'Hardware Accelerated Graphics & High-Resolution Display',
          fontSize: 46,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'center',
          lineHeight: 1.2,
        },
        {
          id: 's5-img',
          type: 'image',
          x: 320,
          y: 170,
          width: 1280,
          height: 640,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          src: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1400&q=80',
          objectFit: 'cover',
          borderRadius: 16,
          shadowBlur: 35,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
        },
        {
          id: 's5-caption',
          type: 'text',
          x: 320,
          y: 840,
          width: 1280,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: 'Engineered for seamless fidelity across desktop workstations, mobile displays, and high-definition projectors.',
          fontSize: 22,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#94a3b8',
          textAlign: 'center',
          lineHeight: 1.5,
        },
      ],
    },

    // Slide 6: Conclusion & Action
    {
      id: 'slide-6',
      title: 'Conclusion & Next Steps',
      layout: 'title-slide',
      background: {
        type: 'linear-gradient',
        color: '#0f172a',
        gradientStart: '#090d16',
        gradientEnd: '#2e1065',
        gradientAngle: 135,
      },
      transition: {
        type: 'wipe-left',
        duration: 0.7,
        easing: 'ease-in-out',
      },
      script: 'Thank you for exploring SlideCast Studio. You can now customize your slides, test different voices, enter fullscreen presentation mode, or export your video in full high definition.',
      duration: 8,
      paddingDuration: 1.2,
      autoAdvance: true,
      elements: [
        {
          id: 's6-tag',
          type: 'text',
          x: 760,
          y: 220,
          width: 400,
          height: 48,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          text: 'READY TO BROADCAST',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#34d399',
          backgroundColor: 'rgba(52, 211, 153, 0.15)',
          textAlign: 'center',
          lineHeight: 1.6,
          borderRadius: 20,
          borderWidth: 1,
          borderColor: 'rgba(52, 211, 153, 0.3)',
          borderStyle: 'solid',
        },
        {
          id: 's6-title',
          type: 'text',
          x: 160,
          y: 310,
          width: 1600,
          height: 180,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          text: 'Start Creating Your Masterpiece',
          fontSize: 72,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#f8fafc',
          textAlign: 'center',
          lineHeight: 1.15,
        },
        {
          id: 's6-sub',
          type: 'text',
          x: 240,
          y: 520,
          width: 1440,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          text: 'Click "Export Video" above to generate your MP4, or press F5 to enter fullscreen presentation mode.',
          fontSize: 28,
          fontFamily: 'Inter, sans-serif',
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#cbd5e1',
          textAlign: 'center',
          lineHeight: 1.5,
        },
        {
          id: 's6-signature',
          type: 'text',
          x: 360,
          y: 670,
          width: 1200,
          height: 60,
          rotation: 0,
          opacity: 0.9,
          zIndex: 4,
          text: 'Thank You • Questions & Discussion',
          fontSize: 24,
          fontFamily: 'Outfit, sans-serif',
          fontWeight: '600',
          fontStyle: 'normal',
          textDecoration: 'none',
          color: '#a78bfa',
          textAlign: 'center',
          lineHeight: 1.4,
        },
      ],
    },
  ],
};
