import { Theme } from '../types/presentation';

export const PRESET_THEMES: Theme[] = [
  {
    id: 'elegant-dark',
    name: 'Elegant Dark',
    description: 'Deep obsidian aesthetic with electric blue accents and architectural contrast',
    background: {
      type: 'solid',
      color: '#0F0F0F',
    },
    primaryColor: '#2563eb',
    secondaryColor: '#60a5fa',
    accentColor: '#3b82f6',
    headingFont: 'Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#ffffff',
    mutedColor: '#9ca3af',
    cardBg: 'rgba(26, 26, 26, 0.95)',
    previewGradient: 'linear-gradient(135deg, #0F0F0F, #1E1E1E)',
  },
  {
    id: 'modern-dark',
    name: 'Modern Dark',
    description: 'Sleek dark obsidian with electric indigo accents',
    background: {
      type: 'linear-gradient',
      color: '#0f172a',
      gradientStart: '#090d16',
      gradientEnd: '#1e1b4b',
      gradientAngle: 135,
    },
    primaryColor: '#6366f1',
    secondaryColor: '#818cf8',
    accentColor: '#38bdf8',
    headingFont: 'Outfit, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#f8fafc',
    mutedColor: '#94a3b8',
    cardBg: 'rgba(30, 41, 59, 0.7)',
    previewGradient: 'linear-gradient(135deg, #090d16, #1e1b4b)',
  },
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    description: 'Clean Scandinavian aesthetic with high readability',
    background: {
      type: 'solid',
      color: '#f8fafc',
    },
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    accentColor: '#2563eb',
    headingFont: 'Plus Jakarta Sans, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#0f172a',
    mutedColor: '#64748b',
    cardBg: 'rgba(255, 255, 255, 0.85)',
    previewGradient: 'linear-gradient(135deg, #ffffff, #e2e8f0)',
  },
  {
    id: 'royal-indigo',
    name: 'Royal Indigo',
    description: 'Deep midnight blue with vibrant ultraviolet highlights',
    background: {
      type: 'linear-gradient',
      color: '#1e1b4b',
      gradientStart: '#0f0a2a',
      gradientEnd: '#31104b',
      gradientAngle: 160,
    },
    primaryColor: '#a855f7',
    secondaryColor: '#c084fc',
    accentColor: '#22d3ee',
    headingFont: 'Outfit, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#fdf4ff',
    mutedColor: '#d8b4fe',
    cardBg: 'rgba(49, 16, 75, 0.65)',
    previewGradient: 'linear-gradient(135deg, #0f0a2a, #31104b)',
  },
  {
    id: 'emerald-tech',
    name: 'Emerald Tech',
    description: 'Deep rich forest with crisp emerald and mint tones',
    background: {
      type: 'linear-gradient',
      color: '#022c22',
      gradientStart: '#022c22',
      gradientEnd: '#064e3b',
      gradientAngle: 140,
    },
    primaryColor: '#10b981',
    secondaryColor: '#34d399',
    accentColor: '#6ee7b7',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#ecfdf5',
    mutedColor: '#a7f3d0',
    cardBg: 'rgba(6, 78, 59, 0.6)',
    previewGradient: 'linear-gradient(135deg, #022c22, #064e3b)',
  },
  {
    id: 'sunset-coral',
    name: 'Sunset Coral',
    description: 'Warm dusk twilight with vibrant coral & rose accents',
    background: {
      type: 'linear-gradient',
      color: '#18181b',
      gradientStart: '#18181b',
      gradientEnd: '#2e1022',
      gradientAngle: 135,
    },
    primaryColor: '#f43f5e',
    secondaryColor: '#fb7185',
    accentColor: '#fb923c',
    headingFont: 'Outfit, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#fff1f2',
    mutedColor: '#fda4af',
    cardBg: 'rgba(46, 16, 34, 0.6)',
    previewGradient: 'linear-gradient(135deg, #18181b, #2e1022)',
  },
  {
    id: 'nordic-slate',
    name: 'Nordic Slate',
    description: 'Cool architectural slate gray with crisp icy cyan',
    background: {
      type: 'linear-gradient',
      color: '#1e293b',
      gradientStart: '#0f172a',
      gradientEnd: '#334155',
      gradientAngle: 120,
    },
    primaryColor: '#38bdf8',
    secondaryColor: '#7dd3fc',
    accentColor: '#818cf8',
    headingFont: 'Plus Jakarta Sans, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#f0f9ff',
    mutedColor: '#94a3b8',
    cardBg: 'rgba(51, 65, 85, 0.65)',
    previewGradient: 'linear-gradient(135deg, #0f172a, #334155)',
  },
  {
    id: 'golden-luxury',
    name: 'Golden Luxury',
    description: 'Opulent dark caviar background with champagne gold accents',
    background: {
      type: 'linear-gradient',
      color: '#141416',
      gradientStart: '#0f0e0c',
      gradientEnd: '#292318',
      gradientAngle: 145,
    },
    primaryColor: '#eab308',
    secondaryColor: '#fde047',
    accentColor: '#d97706',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Outfit, sans-serif',
    textColor: '#fefce8',
    mutedColor: '#ca8a04',
    cardBg: 'rgba(41, 35, 24, 0.7)',
    previewGradient: 'linear-gradient(135deg, #0f0e0c, #292318)',
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'High-contrast futuristic neon pink & electric cyan',
    background: {
      type: 'linear-gradient',
      color: '#09090b',
      gradientStart: '#09090b',
      gradientEnd: '#130424',
      gradientAngle: 135,
    },
    primaryColor: '#ec4899',
    secondaryColor: '#06b6d4',
    accentColor: '#a855f7',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Fira Code, monospace',
    textColor: '#fdf2f8',
    mutedColor: '#f472b6',
    cardBg: 'rgba(19, 4, 36, 0.75)',
    previewGradient: 'linear-gradient(135deg, #09090b, #130424)',
  },
  {
    id: 'oceanic-breeze',
    name: 'Oceanic Breeze',
    description: 'Deep abyss blue with vibrant turquoise aquatic tones',
    background: {
      type: 'linear-gradient',
      color: '#082f49',
      gradientStart: '#051928',
      gradientEnd: '#0e4a6f',
      gradientAngle: 150,
    },
    primaryColor: '#06b6d4',
    secondaryColor: '#22d3ee',
    accentColor: '#38bdf8',
    headingFont: 'Outfit, sans-serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#f0fdfa',
    mutedColor: '#67e8f9',
    cardBg: 'rgba(14, 74, 111, 0.6)',
    previewGradient: 'linear-gradient(135deg, #051928, #0e4a6f)',
  },
  {
    id: 'crimson-editorial',
    name: 'Crimson Editorial',
    description: 'Sophisticated vintage editorial burgundy with warm cream',
    background: {
      type: 'linear-gradient',
      color: '#450a0a',
      gradientStart: '#2d0505',
      gradientEnd: '#591111',
      gradientAngle: 135,
    },
    primaryColor: '#f87171',
    secondaryColor: '#fca5a5',
    accentColor: '#f59e0b',
    headingFont: 'Merriweather, serif',
    bodyFont: 'Inter, sans-serif',
    textColor: '#fff5f5',
    mutedColor: '#fca5a5',
    cardBg: 'rgba(89, 17, 17, 0.65)',
    previewGradient: 'linear-gradient(135deg, #2d0505, #591111)',
  },
];
